OBJECTS = avs2yuv64.o
BIN = avs2yuv64.exe

CXX=x86_64-w64-mingw32-gcc

CXXFLAGS=-I. -std=gnu99 -Wall -O3 -msse2 -mfpmath=sse -ffast-math -fno-math-errno -flto -fomit-frame-pointer
LDFLAGS=

all: $(BIN)

%64.o : %.c
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(BIN) : $(OBJECTS)
	$(CXX) $(OBJECTS) -s -o $(BIN)

clean :
	rm -f $(OBJECTS) $(BIN)

avs2yuv64.o: avs2yuv.c
