OBJECTS = avs2yuv.o
BIN = avs2yuv.exe

CXX=i686-w64-mingw32-gcc

CXXFLAGS=-Wall -std=c99 -I. -std=gnu99 -O3 -msse -mfpmath=sse -ffast-math -fno-math-errno -flto -fomit-frame-pointer
LDFLAGS=--large-address-aware

all: $(BIN)

%.o : %.c
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(BIN) : $(OBJECTS)
	$(CXX) $(OBJECTS) -s -o $(BIN)

clean :
	rm -f $(OBJECTS) $(BIN)

avs2yuv.o: avs2yuv.c
